import React, { useState } from 'react'

export default function ShareButton({ url, score, results, verdict }) {
  const [copied, setCopied] = useState(false)

  function buildReport() {
    const passed = results.filter(r => r.status === 'pass').map(r => `  • ${r.label}`)
    const warnings = results.filter(r => r.status === 'warning').map(r => `  • ${r.label}`)
    const failed = results.filter(r => r.status === 'fail').map(r => `  • ${r.label}`)

    const recommendations = results
      .filter(r => r.status === 'fail' || r.status === 'warning')
      .map(r => `  • ${r.label}: ${r.detail}`)

    const lines = [
      'ShipCheck Report',
      '================',
      '',
      `URL: ${url}`,
      `Launch Score: ${score}/100`,
      '',
      'Passed:',
      passed.length > 0 ? passed.join('\n') : '  (none)',
      '',
      'Warnings:',
      warnings.length > 0 ? warnings.join('\n') : '  (none)',
      '',
      'Failed:',
      failed.length > 0 ? failed.join('\n') : '  (none)',
      '',
      'Recommendations:',
      recommendations.length > 0 ? recommendations.join('\n') : '  No recommendations — great work!',
      '',
      `Verdict: ${verdict}`,
      '',
      'Generated by ShipCheck — https://createos.sh'
    ]

    return lines.join('\n')
  }

  async function handleCopy() {
    if (copied) return
    try {
      await navigator.clipboard.writeText(buildReport())
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea')
      textarea.value = buildReport()
      textarea.style.position = 'fixed'
      textarea.style.opacity = '0'
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <button
      onClick={handleCopy}
      style={{
        ...styles.button,
        background: copied
          ? 'rgba(34, 197, 94, 0.15)'
          : 'rgba(99, 102, 241, 0.12)',
        borderColor: copied
          ? 'rgba(34, 197, 94, 0.35)'
          : 'rgba(99, 102, 241, 0.35)',
        color: copied ? '#22c55e' : '#a5b4fc'
      }}
      aria-label="Copy report to clipboard"
    >
      <span style={styles.icon}>{copied ? '✓' : '📋'}</span>
      {copied ? 'Copied!' : 'Copy Report'}
    </button>
  )
}

const styles = {
  button: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    borderRadius: '8px',
    border: '1px solid',
    fontSize: '14px',
    fontWeight: 600,
    fontFamily: "'DM Sans', system-ui, sans-serif",
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    letterSpacing: '-0.01em'
  },
  icon: {
    fontSize: '15px'
  }
}
